### ISSUE TITLE
Add autocomplete and highlighting feature on headers, body and basic auth username text boxes

### ISSUE THREAD

**Issue by fatihbaltaci** [ddosify/ddosify-docker-extension#11]
@Le-Roi777 added support for autocomplete and highlighting on target URL 🙏

<img width="985" alt="image" src="https://user-images.githubusercontent.com/10353650/197286664-93d7f684-67da-43d6-bb7d-a8dfdca079dc.png">

But Headers, Body and Basic Auth Username text boxes do not contain autocomplete and highlighting features. 

<img width="985" alt="image" src="https://user-images.githubusercontent.com/10353650/197287354-76a08d6a-50a1-4f24-a7db-a170d8ba03c6.png">

Also, autocomplete must be case insensitive like [Ddosify Cloud](https://app.ddosify.com/). 

<img width="561" alt="image" src="https://user-images.githubusercontent.com/10353650/197287949-d7af4169-b810-474f-8db0-31add9dcd5df.png">

**Comment by Lalit3716** [comment]
Hi @fatihbaltaci , it would be a good feature indeed. I want to give it a try can you assign me this?

**Comment by fatihbaltaci** [comment]
Sure @Lalit3716, I assigned this issue to you, thanks!
