### ISSUE TITLE
Download Test Results Report as PDF

### ISSUE THREAD

**Issue by fatihbaltaci** [ddosify/ddosify-docker-extension#3]
Users should be able to download test **results** and **configurations** as PDF. There should be a button named `Download Test Results`.

**Comment by varun7singh** [comment]
im working on it

**Comment by gagandeepp** [comment]
interested please assign

**Comment by fatihbaltaci** [comment]
Hi @gagandeepp, I assigned this issue to you, thanks.

**Comment by fatihbaltaci** [comment]
This is a sample report example: https://ddosify-assets.s3.eu-central-1.amazonaws.com/Load+Test+Results.pdf

**Comment by gagandeepp** [comment]
https://github.com/ddosify/ddosify-docker-extension/pull/6

**Comment by gagandeepp** [comment]
@fatihbaltaci  please review my PR

https://github.com/ddosify/ddosify-docker-extension/pull/6

**Comment by fatihbaltaci** [comment]
Hi @gagandeepp, thanks for your contribution. I successfully downloaded the report. But the report should look similar to the sample report I shared in the previous message. Could you please change that? 

**The result:** 
![image](https://user-images.githubusercontent.com/10353650/194026832-20df5e35-f529-4b38-b15a-57808eb90f9c.png)

**Expected:** 
https://ddosify-assets.s3.eu-central-1.amazonaws.com/Load+Test+Results.pdf

Thanks

**Comment by gagandeepp** [comment]
In the above report there is a configuration as well . I am not sure how to get values for those parameters.
Or May be I can just write the result in the pdf excluding runs. Sounds Good?

**Comment by fatihbaltaci** [comment]
You can get the configuration from this state: https://github.com/ddosify/ddosify-docker-extension/blob/main/ui/src/App.js#L85

And I think, the result can be parsable from this line: https://github.com/ddosify/ddosify-docker-extension/blob/main/ui/src/App.js#L234

**Comment by gagandeepp** [comment]
@fatihbaltaci  Please review again
