### ISSUE TITLE
Highlight dynamic variables

### ISSUE THREAD

**Issue by kursataktas** [ddosify/ddosify-docker-extension#4]
Just like on Ddosify Cloud, it would be great if Ddosify Docker Extension has this UX capability.
![image](https://user-images.githubusercontent.com/17837825/193425101-52773d61-7cee-4e22-9667-223a2efeb2ab.png)

- Autocomplete is a big plus.
- [About dynamic variables.](https://github.com/ddosify/ddosify#parameterization-dynamic-variables)

**Comment by sristis0202** [comment]
Hi! I am a beginner to open source and would like to take this issue up for Hacktoberfest'22. Kindly assign me.

**Comment by fatihbaltaci** [comment]
Hi @sristis0202, I assigned this issue to you, thanks.

**Comment by Le-Roi777** [comment]
Hi @fatihbaltaci may I also work on this?

**Comment by fatihbaltaci** [comment]
Hi @sristis0202, are you working on this issue?

**Comment by Le-Roi777** [comment]
Hey guys :-)
Any updates on this?

**Comment by fatihbaltaci** [comment]
Hey @Le-Roi777, I will assign this issue to you if I do not hear back from @sristis0202 for two days

**Comment by Le-Roi777** [comment]
> Hey @Le-Roi777, I will assign this issue to you if I do not hear back from @sristis0202 for two days

👍

**Comment by Le-Roi777** [comment]
I'd be happy to jump on this issue as well :-)
https://github.com/ddosify/ddosify-docker-extension/issues/5

**Comment by fatihbaltaci** [comment]
Hey @Le-Roi777, I assigned this issue to you. Thanks for your support.

**Comment by Le-Roi777** [comment]
> Hey @Le-Roi777, I assigned this issue to you. Thanks for your support.

Awesome 👍 keep you guys posted
