### ISSUE TITLE
Autocomplete feature for Headers

### ISSUE THREAD

**Issue by kursataktas** [ddosify/ddosify-docker-extension#5]
Currently request headers form is too manual.
<img width="967" alt="image" src="https://user-images.githubusercontent.com/17837825/193425198-5b2dcc54-b25b-441d-82d9-27b1a1eb1a9b.png">

Postman-like autocompletion would make the end user's job easier.
![image](https://user-images.githubusercontent.com/17837825/193425220-185dd262-433d-4721-9e41-6af4ea74b2ee.png)

**Comment by ighmaZ** [comment]
@kursataktas would love to work on this

**Comment by kursataktas** [comment]
Sure  @ighmaZ. I assigned it to you, thanks

**Comment by Le-Roi777** [comment]
Hey guys :-)
Any updates? @kursataktas may I also work on this ?

**Comment by kursataktas** [comment]
@ighmaZ are you working on this issue?

**Comment by kursataktas** [comment]
@Le-Roi777 I've assigned this issue to you

**Comment by Le-Roi777** [comment]
> @Le-Roi777 I've assigned this issue to you
👍

**Comment by kursataktas** [comment]
Closed with #8
