### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by boradesanket13** [ddosify/ddosify-docker-extension#7]
CONTRIBUTING.md is a must read file for a new contributor in any repository before starting to work.

- Add general good practices while starting to work with this specific project.
- Add standard Github workflow commands in the CONTRIBUTING.md (opening issues, get assigned, fork, create clone, add, commit, creating PRs).
- It will provide new potential project contributors with a short guide to how they can help with your project.

**Comment by fatihbaltaci** [comment]
Hi @Sanket1308, thanks for your comments, we will add the `CONTRIBUTING.md` soon.

**Comment by boradesanket13** [comment]
@fatihbaltaci kindly assign me this issue under hacktoberfest. I would like to work on it.🚀

**Comment by fatihbaltaci** [comment]
Great, I assigned this issue to you
